<?php

$finder = PhpCsFixer\Finder::create()
    ->in('hooks')
    ->notPath(['Kernel.php']);

return PhpCsFixer\Config::create()
    ->setRules(
        [
            '@PSR2' => true,
            'array_syntax' => ['syntax' => 'short'],
            'dir_constant' => true,
            'heredoc_to_nowdoc' => true,
            'linebreak_after_opening_tag' => true,
            'modernize_types_casting' => true,
            'no_multiline_whitespace_before_semicolons' => true,
            'no_unreachable_default_argument_value' => true,
            'no_useless_else' => true,
            'no_useless_return' => true,
            'ordered_class_elements' => true,
            'phpdoc_add_missing_param_annotation' => ['only_untyped' => true],
            'phpdoc_order' => true,
            'declare_strict_types' => true,
            'doctrine_annotation_braces' => true,
            'doctrine_annotation_indentation' => true,
            'doctrine_annotation_spaces' => true,
            'psr4' => true,
            'no_php4_constructor' => true,
            'no_short_echo_tag' => true,
            'semicolon_after_instruction' => true,
            'align_multiline_comment' => true,
            'doctrine_annotation_array_assignment' => true,
            'general_phpdoc_annotation_remove' => ['annotations' => ["author", "package"]],
            'list_syntax' => ["syntax" => "short"],
            'phpdoc_types_order' => ['null_adjustment' => 'always_last'],
            'single_line_comment_style' => true,
            'binary_operator_spaces' => true,
            'blank_line_after_opening_tag' => true,
            'blank_line_before_return' => true,
            'cast_spaces' => true,
            'combine_consecutive_unsets' => true,
            'concat_space' => [
                'spacing' => 'one',
            ],
            'declare_equal_normalize' => [
                'space' => 'none',
            ],
            'function_to_constant' => true,
            'include' => true,
            'lowercase_cast' => true,
            'magic_constant_casing' => true,
            'mb_str_functions' => true,
            'method_separation' => true,
            'native_function_casing' => true,
            'new_with_braces' => true,
            'no_alias_functions' => true,
            'no_blank_lines_after_class_opening' => true,
            'no_blank_lines_after_phpdoc' => true,
            'no_empty_comment' => true,
            'no_empty_phpdoc' => true,
            'no_empty_statement' => true,
            'no_extra_consecutive_blank_lines' => true,
            'no_leading_import_slash' => true,
            'no_leading_namespace_whitespace' => true,
            'no_mixed_echo_print' => true,
            'no_multiline_whitespace_around_double_arrow' => true,
            'no_short_bool_cast' => true,
            'no_singleline_whitespace_before_semicolons' => true,
            'no_spaces_around_offset' => true,
            'no_trailing_comma_in_list_call' => true,
            'no_trailing_comma_in_singleline_array' => true,
            'no_unneeded_control_parentheses' => true,
            'no_unused_imports' => true,
            'no_whitespace_before_comma_in_array' => true,
            'no_whitespace_in_blank_line' => true,
            'non_printable_character' => true,
            'normalize_index_brace' => true,
            'php_unit_construct' => true,
            'php_unit_dedicate_assert' => true,
            'php_unit_fqcn_annotation' => true,
            'php_unit_strict' => true,
            'php_unit_test_class_requires_covers' => true,
            'phpdoc_align' => true,
            'phpdoc_annotation_without_dot' => true,
            'phpdoc_indent' => true,
            'phpdoc_inline_tag' => true,
            'phpdoc_no_access' => true,
            'phpdoc_no_alias_tag' => true,
            'phpdoc_no_empty_return' => true,
            'phpdoc_no_package' => true,
            'phpdoc_no_useless_inheritdoc' => true,
            'phpdoc_return_self_reference' => true,
            'phpdoc_scalar' => true,
            'phpdoc_separation' => true,
            'phpdoc_single_line_var_spacing' => true,
            'phpdoc_summary' => true,
            'phpdoc_to_comment' => true,
            'phpdoc_trim' => true,
            'phpdoc_types' => true,
            'phpdoc_var_without_name' => true,
            'pow_to_exponentiation' => true,
            'increment_style' => ['style' => 'post'],
            'protected_to_private' => true,
            'psr0' => true,
            'random_api_migration' => true,
            'return_type_declaration' => [
                'space_before' => 'one',
            ],
            'self_accessor' => true,
            'short_scalar_cast' => true,
            'silenced_deprecation_error' => true,
            'simplified_null_return' => true,
            'single_quote' => true,
            'space_after_semicolon' => true,
            'standardize_not_equals' => true,
            'strict_comparison' => true,
            'strict_param' => true,
            'ternary_operator_spaces' => true,
            'ternary_to_null_coalescing' => true,
            'trailing_comma_in_multiline_array' => true,
            'trim_array_spaces' => true,
            'unary_operator_spaces' => true,
            'whitespace_after_comma_in_array' => true,
        ]
    )
    ->setFinder($finder);
